package com.point.entity.pdf;

import com.point.common.CommonFunc;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;

@Data
public class StabilityEnity_LTTArmEntity {
    private String sjht;

    private String no;
    private String ver;
    private String xmmc;
    private String zjxh;
    private String jsr;
    private String shr;
    private String pzr;
    private String date;

    private Double h;
    private Double pf;

    private Double lbd;
    private Double lbx;
    private Double lbp;
    private Double lg;
    private Double ll;
    private Double gxh;
    private Double dbyj;
    private Double mzj;
    private Double mzjf;

    private String gdlsxh;
    private Double flsjl;
    private Double nwd1;
    private Double nwd2;
    private String txxxh;
    private String txxdj;
    private Double ftxxjq;
    private Double nwdt;

    private String djlsxh;
    private Double lsgca;
    private Double fdjlsfb;
    private Double nwd4;
    private Double nwd3;
    private Double fdjlszfb;

    private Double swp;
    private Double r1;
    private Double mwr;
    private Double tsl;
    private Double hwll;
    private Double hsw;
    private Double tshl;
    private Double m1;
    private Double m2;
    private Double m3;
    private Double m4;
    private Double m5;
    private Double m6;
    private Double m7;
    private Double m8;
    private Double m9;
    private Double m10;
    private Double m11;
    private Double m12;
    private Double m13;
    private Double m14;
    private Double m15;

    private String qt1;
    private String qt2;
    private String qt1y;
    private String qt2y;

    private Double lslhz;
    private Double lshlhz;
    private Double lhz1;
    private Double lhz2;
    private Double lhz3;
    private Double lhz4;
    private Double lhz5;
    private Double lhz6;
    private Double lhz7;
    private Double lhz8;
    private Double lhz9;
    private Double lhz10;
    private Double lhz11;
    private Double lhz12;
    private Double lhz13;
    private Double lhz14;
    private Double lhz15;

    private Double lslqg;
    private Double lshlqg;
    private Double lqg1;
    private Double lqg2;
    private Double lqg3;
    private Double lqg4;
    private Double lqg5;
    private Double lqg6;
    private Double lqg7;
    private Double lqg8;
    private Double lqg9;
    private Double lqg10;
    private Double lqg11;
    private Double lqg12;
    private Double lqg13;
    private Double lqg14;
    private Double lqg15;

    private Double lslql;
    private Double lshlql;
    private Double lql1;
    private Double lql2;
    private Double lql3;
    private Double lql4;
    private Double lql5;
    private Double lql6;
    private Double lql7;
    private Double lql8;
    private Double lql9;
    private Double lql10;
    private Double lql11;
    private Double lql12;
    private Double lql13;
    private Double lql14;
    private Double lql15;

    private Double hslg;
    private Double hshlg;
    private Double hg1;
    private Double hg2;
    private Double hg3;
    private Double hg4;
    private Double hg5;
    private Double hg6;
    private Double hg7;
    private Double hg8;
    private Double hg9;
    private Double hg10;
    private Double hg11;
    private Double hg12;
    private Double hg13;
    private Double hg14;
    private Double hg15;

    private Double aslcx;
    private Double ashlcx;
    private Double acx1;
    private Double acx2;
    private Double acx3;
    private Double acx4;
    private Double acx5;
    private Double acx6;
    private Double acx7;
    private Double acx8;
    private Double acx9;
    private Double acx10;
    private Double acx11;
    private Double acx12;
    private Double acx13;
    private Double acx14;
    private Double acx15;

    private Double asltx;
    private Double ashltx;
    private Double atx1;
    private Double atx2;
    private Double atx3;
    private Double atx4;
    private Double atx5;
    private Double atx6;
    private Double atx7;
    private Double atx8;
    private Double atx9;
    private Double atx10;
    private Double atx11;
    private Double atx12;
    private Double atx13;
    private Double atx14;
    private Double atx15;

    private Double lhzf1;
    private Double lhzf2;
    private Double lhzf3;
    private Double lhzf4;
    private Double lhzf5;
    private Double lhzf6;
    private Double lhzf7;
    private Double lhzf8;
    private Double lhzf9;
    private Double lhzf10;
    private Double lhzf11;
    private Double lhzf12;
    private Double lhzf13;
    private Double lhzf14;
    private Double lhzf15;

    private Double lhl1;
    private Double lhl2;
    private Double lhl3;
    private Double lhl4;
    private Double lhl5;
    private Double lhl6;
    private Double lhl7;
    private Double lhl8;
    private Double lhl9;
    private Double lhl10;
    private Double lhl11;
    private Double lhl12;
    private Double lhl13;
    private Double lhl14;
    private Double lhl15;

    private Double hgf1;
    private Double hgf2;
    private Double hgf3;
    private Double hgf4;
    private Double hgf5;
    private Double hgf6;
    private Double hgf7;
    private Double hgf8;
    private Double hgf9;
    private Double hgf10;
    private Double hgf11;
    private Double hgf12;
    private Double hgf13;
    private Double hgf14;
    private Double hgf15;

    private Double afcx1;
    private Double afcx2;
    private Double afcx3;
    private Double afcx4;
    private Double afcx5;
    private Double afcx6;
    private Double afcx7;
    private Double afcx8;
    private Double afcx9;
    private Double afcx10;
    private Double afcx11;
    private Double afcx12;
    private Double afcx13;
    private Double afcx14;
    private Double afcx15;

    private Double aftx1;
    private Double aftx2;
    private Double aftx3;
    private Double aftx4;
    private Double aftx5;
    private Double aftx6;
    private Double aftx7;
    private Double aftx8;
    private Double aftx9;
    private Double aftx10;
    private Double aftx11;
    private Double aftx12;
    private Double aftx13;
    private Double aftx14;
    private Double aftx15;

    //Select
    private String typeOfMachine;
    private String haveOfMobileCounterweight;
    private String typeOfRunningGear;
    private String typeOfPin;
    private String levelOfPin;
    private String typeOfBolt;
    private String typeOfLifting;
    private String typeOfGRU;
    private String wdlyp3;

    private Map<String, String> createMap() {
        Map<String, String> result = new HashMap<>();
        result.put("mzjf", CommonFunc.convertDoubleToString(mzjf));
        result.put("sjht", CommonFunc.convertDoubleToString(sjht));
        result.put("no", CommonFunc.convertDoubleToString(no));
        result.put("ver", CommonFunc.convertDoubleToString(ver));
        result.put("xmmc", CommonFunc.convertDoubleToString(xmmc));
        result.put("zjxh", CommonFunc.convertDoubleToString(zjxh));
        result.put("jsr", CommonFunc.convertDoubleToString(jsr));
        result.put("shr", CommonFunc.convertDoubleToString(shr));
        result.put("pzr", CommonFunc.convertDoubleToString(pzr));
        result.put("date", CommonFunc.convertDoubleToString(date));
        result.put("h", CommonFunc.convertDoubleToString(h));
        result.put("pf", CommonFunc.convertDoubleToString(pf));
        result.put("lbd", CommonFunc.convertDoubleToString(lbd));
        result.put("lbx", CommonFunc.convertDoubleToString(lbx));
        result.put("lbp", CommonFunc.convertDoubleToString(lbp));
        result.put("lg", CommonFunc.convertDoubleToString(lg));
        result.put("ll", CommonFunc.convertDoubleToString(ll));
        result.put("gxh", CommonFunc.convertDoubleToString(gxh));
        result.put("dbyj", CommonFunc.convertDoubleToString(dbyj));
        result.put("mzj", CommonFunc.convertDoubleToString(mzj));
        result.put("gdlsxh", CommonFunc.convertDoubleToString(gdlsxh));
        result.put("flsjl", CommonFunc.convertDoubleToString(flsjl));
        result.put("nwd1", CommonFunc.convertDoubleToString(nwd1));
        result.put("nwd2", CommonFunc.convertDoubleToString(nwd2));
        result.put("txxxh", CommonFunc.convertDoubleToString(txxxh));
        result.put("txxdj", CommonFunc.convertDoubleToString(txxdj));
        result.put("ftxxjq", CommonFunc.convertDoubleToString(ftxxjq));
        result.put("nwdt", CommonFunc.convertDoubleToString(nwdt));
        result.put("djlsxh", CommonFunc.convertDoubleToString(djlsxh));
        result.put("lsgca", CommonFunc.convertDoubleToString(lsgca));
        result.put("fdjlsfb", CommonFunc.convertDoubleToString(fdjlsfb));
        result.put("nwd4", CommonFunc.convertDoubleToString(nwd4));
        result.put("nwd3", CommonFunc.convertDoubleToString(nwd3));
        result.put("fdjlszfb", CommonFunc.convertDoubleToString(fdjlszfb));
        result.put("swp", CommonFunc.convertDoubleToString(swp));
        result.put("r1", CommonFunc.convertDoubleToString(r1));
        result.put("mwr", CommonFunc.convertDoubleToString(mwr));
        result.put("tsl", CommonFunc.convertDoubleToString(tsl));
        result.put("hwll", CommonFunc.convertDoubleToString(hwll));
        result.put("hsw", CommonFunc.convertDoubleToString(hsw));
        result.put("tshl", CommonFunc.convertDoubleToString(tshl));
        result.put("m1", CommonFunc.convertDoubleToString(m1));
        result.put("m2", CommonFunc.convertDoubleToString(m2));
        result.put("m3", CommonFunc.convertDoubleToString(m3));
        result.put("m4", CommonFunc.convertDoubleToString(m4));
        result.put("m5", CommonFunc.convertDoubleToString(m5));
        result.put("m6", CommonFunc.convertDoubleToString(m6));
        result.put("m7", CommonFunc.convertDoubleToString(m7));
        result.put("m8", CommonFunc.convertDoubleToString(m8));
        result.put("m9", CommonFunc.convertDoubleToString(m9));
        result.put("m10", CommonFunc.convertDoubleToString(m10));
        result.put("m11", CommonFunc.convertDoubleToString(m11));
        result.put("m12", CommonFunc.convertDoubleToString(m12));
        result.put("m13", CommonFunc.convertDoubleToString(m13));
        result.put("m14", CommonFunc.convertDoubleToString(m14));
        result.put("m15", CommonFunc.convertDoubleToString(m15));
        result.put("qt1", CommonFunc.convertDoubleToString(qt1));
        result.put("qt2", CommonFunc.convertDoubleToString(qt2));
        result.put("qt1y", CommonFunc.convertDoubleToString(qt1y));
        result.put("qt2y", CommonFunc.convertDoubleToString(qt2y));
        result.put("lslhz", CommonFunc.convertDoubleToString(lslhz));
        result.put("lshlhz", CommonFunc.convertDoubleToString(lshlhz));
        result.put("lhz1", CommonFunc.convertDoubleToString(lhz1));
        result.put("lhz2", CommonFunc.convertDoubleToString(lhz2));
        result.put("lhz3", CommonFunc.convertDoubleToString(lhz3));
        result.put("lhz4", CommonFunc.convertDoubleToString(lhz4));
        result.put("lhz5", CommonFunc.convertDoubleToString(lhz5));
        result.put("lhz6", CommonFunc.convertDoubleToString(lhz6));
        result.put("lhz7", CommonFunc.convertDoubleToString(lhz7));
        result.put("lhz8", CommonFunc.convertDoubleToString(lhz8));
        result.put("lhz9", CommonFunc.convertDoubleToString(lhz9));
        result.put("lhz10", CommonFunc.convertDoubleToString(lhz10));
        result.put("lhz11", CommonFunc.convertDoubleToString(lhz11));
        result.put("lhz12", CommonFunc.convertDoubleToString(lhz12));
        result.put("lhz13", CommonFunc.convertDoubleToString(lhz13));
        result.put("lhz14", CommonFunc.convertDoubleToString(lhz14));
        result.put("lhz15", CommonFunc.convertDoubleToString(lhz15));
        result.put("lslqg", CommonFunc.convertDoubleToString(lslqg));
        result.put("lshlqg", CommonFunc.convertDoubleToString(lshlqg));
        result.put("lqg1", CommonFunc.convertDoubleToString(lqg1));
        result.put("lqg2", CommonFunc.convertDoubleToString(lqg2));
        result.put("lqg3", CommonFunc.convertDoubleToString(lqg3));
        result.put("lqg4", CommonFunc.convertDoubleToString(lqg4));
        result.put("lqg5", CommonFunc.convertDoubleToString(lqg5));
        result.put("lqg6", CommonFunc.convertDoubleToString(lqg6));
        result.put("lqg7", CommonFunc.convertDoubleToString(lqg7));
        result.put("lqg8", CommonFunc.convertDoubleToString(lqg8));
        result.put("lqg9", CommonFunc.convertDoubleToString(lqg9));
        result.put("lqg10", CommonFunc.convertDoubleToString(lqg10));
        result.put("lqg11", CommonFunc.convertDoubleToString(lqg11));
        result.put("lqg12", CommonFunc.convertDoubleToString(lqg12));
        result.put("lqg13", CommonFunc.convertDoubleToString(lqg13));
        result.put("lqg14", CommonFunc.convertDoubleToString(lqg14));
        result.put("lqg15", CommonFunc.convertDoubleToString(lqg15));
        result.put("lslql", CommonFunc.convertDoubleToString(lslql));
        result.put("lshlql", CommonFunc.convertDoubleToString(lshlql));
        result.put("lql1", CommonFunc.convertDoubleToString(lql1));
        result.put("lql2", CommonFunc.convertDoubleToString(lql2));
        result.put("lql3", CommonFunc.convertDoubleToString(lql3));
        result.put("lql4", CommonFunc.convertDoubleToString(lql4));
        result.put("lql5", CommonFunc.convertDoubleToString(lql5));
        result.put("lql6", CommonFunc.convertDoubleToString(lql6));
        result.put("lql7", CommonFunc.convertDoubleToString(lql7));
        result.put("lql8", CommonFunc.convertDoubleToString(lql8));
        result.put("lql9", CommonFunc.convertDoubleToString(lql9));
        result.put("lql10", CommonFunc.convertDoubleToString(lql10));
        result.put("lql11", CommonFunc.convertDoubleToString(lql11));
        result.put("lql12", CommonFunc.convertDoubleToString(lql12));
        result.put("lql13", CommonFunc.convertDoubleToString(lql13));
        result.put("lql14", CommonFunc.convertDoubleToString(lql14));
        result.put("lql15", CommonFunc.convertDoubleToString(lql15));
        result.put("hslg", CommonFunc.convertDoubleToString(hslg));
        result.put("hshlg", CommonFunc.convertDoubleToString(hshlg));
        result.put("hg1", CommonFunc.convertDoubleToString(hg1));
        result.put("hg2", CommonFunc.convertDoubleToString(hg2));
        result.put("hg3", CommonFunc.convertDoubleToString(hg3));
        result.put("hg4", CommonFunc.convertDoubleToString(hg4));
        result.put("hg5", CommonFunc.convertDoubleToString(hg5));
        result.put("hg6", CommonFunc.convertDoubleToString(hg6));
        result.put("hg7", CommonFunc.convertDoubleToString(hg7));
        result.put("hg8", CommonFunc.convertDoubleToString(hg8));
        result.put("hg9", CommonFunc.convertDoubleToString(hg9));
        result.put("hg10", CommonFunc.convertDoubleToString(hg10));
        result.put("hg11", CommonFunc.convertDoubleToString(hg11));
        result.put("hg12", CommonFunc.convertDoubleToString(hg12));
        result.put("hg13", CommonFunc.convertDoubleToString(hg13));
        result.put("hg14", CommonFunc.convertDoubleToString(hg14));
        result.put("hg15", CommonFunc.convertDoubleToString(hg15));
        result.put("aslcx", CommonFunc.convertDoubleToString(aslcx));
        result.put("ashlcx", CommonFunc.convertDoubleToString(ashlcx));
        result.put("acx1", CommonFunc.convertDoubleToString(acx1));
        result.put("acx2", CommonFunc.convertDoubleToString(acx2));
        result.put("acx3", CommonFunc.convertDoubleToString(acx3));
        result.put("acx4", CommonFunc.convertDoubleToString(acx4));
        result.put("acx5", CommonFunc.convertDoubleToString(acx5));
        result.put("acx6", CommonFunc.convertDoubleToString(acx6));
        result.put("acx7", CommonFunc.convertDoubleToString(acx7));
        result.put("acx8", CommonFunc.convertDoubleToString(acx8));
        result.put("acx9", CommonFunc.convertDoubleToString(acx9));
        result.put("acx10", CommonFunc.convertDoubleToString(acx10));
        result.put("acx11", CommonFunc.convertDoubleToString(acx11));
        result.put("acx12", CommonFunc.convertDoubleToString(acx12));
        result.put("acx13", CommonFunc.convertDoubleToString(acx13));
        result.put("acx14", CommonFunc.convertDoubleToString(acx14));
        result.put("acx15", CommonFunc.convertDoubleToString(acx15));
        result.put("asltx", CommonFunc.convertDoubleToString(asltx));
        result.put("ashltx", CommonFunc.convertDoubleToString(ashltx));
        result.put("atx1", CommonFunc.convertDoubleToString(atx1));
        result.put("atx2", CommonFunc.convertDoubleToString(atx2));
        result.put("atx3", CommonFunc.convertDoubleToString(atx3));
        result.put("atx4", CommonFunc.convertDoubleToString(atx4));
        result.put("atx5", CommonFunc.convertDoubleToString(atx5));
        result.put("atx6", CommonFunc.convertDoubleToString(atx6));
        result.put("atx7", CommonFunc.convertDoubleToString(atx7));
        result.put("atx8", CommonFunc.convertDoubleToString(atx8));
        result.put("atx9", CommonFunc.convertDoubleToString(atx9));
        result.put("atx10", CommonFunc.convertDoubleToString(atx10));
        result.put("atx11", CommonFunc.convertDoubleToString(atx11));
        result.put("atx12", CommonFunc.convertDoubleToString(atx12));
        result.put("atx13", CommonFunc.convertDoubleToString(atx13));
        result.put("atx14", CommonFunc.convertDoubleToString(atx14));
        result.put("atx15", CommonFunc.convertDoubleToString(atx15));
        result.put("lhzf1", CommonFunc.convertDoubleToString(lhzf1));
        result.put("lhzf2", CommonFunc.convertDoubleToString(lhzf2));
        result.put("lhzf3", CommonFunc.convertDoubleToString(lhzf3));
        result.put("lhzf4", CommonFunc.convertDoubleToString(lhzf4));
        result.put("lhzf5", CommonFunc.convertDoubleToString(lhzf5));
        result.put("lhzf6", CommonFunc.convertDoubleToString(lhzf6));
        result.put("lhzf7", CommonFunc.convertDoubleToString(lhzf7));
        result.put("lhzf8", CommonFunc.convertDoubleToString(lhzf8));
        result.put("lhzf9", CommonFunc.convertDoubleToString(lhzf9));
        result.put("lhzf10", CommonFunc.convertDoubleToString(lhzf10));
        result.put("lhzf11", CommonFunc.convertDoubleToString(lhzf11));
        result.put("lhzf12", CommonFunc.convertDoubleToString(lhzf12));
        result.put("lhzf13", CommonFunc.convertDoubleToString(lhzf13));
        result.put("lhzf14", CommonFunc.convertDoubleToString(lhzf14));
        result.put("lhzf15", CommonFunc.convertDoubleToString(lhzf15));
        result.put("lhl1", CommonFunc.convertDoubleToString(lhl1));
        result.put("lhl2", CommonFunc.convertDoubleToString(lhl2));
        result.put("lhl3", CommonFunc.convertDoubleToString(lhl3));
        result.put("lhl4", CommonFunc.convertDoubleToString(lhl4));
        result.put("lhl5", CommonFunc.convertDoubleToString(lhl5));
        result.put("lhl6", CommonFunc.convertDoubleToString(lhl6));
        result.put("lhl7", CommonFunc.convertDoubleToString(lhl7));
        result.put("lhl8", CommonFunc.convertDoubleToString(lhl8));
        result.put("lhl9", CommonFunc.convertDoubleToString(lhl9));
        result.put("lhl10", CommonFunc.convertDoubleToString(lhl10));
        result.put("lhl11", CommonFunc.convertDoubleToString(lhl11));
        result.put("lhl12", CommonFunc.convertDoubleToString(lhl12));
        result.put("lhl13", CommonFunc.convertDoubleToString(lhl13));
        result.put("lhl14", CommonFunc.convertDoubleToString(lhl14));
        result.put("lhl15", CommonFunc.convertDoubleToString(lhl15));
        result.put("hgf1", CommonFunc.convertDoubleToString(hgf1));
        result.put("hgf2", CommonFunc.convertDoubleToString(hgf2));
        result.put("hgf3", CommonFunc.convertDoubleToString(hgf3));
        result.put("hgf4", CommonFunc.convertDoubleToString(hgf4));
        result.put("hgf5", CommonFunc.convertDoubleToString(hgf5));
        result.put("hgf6", CommonFunc.convertDoubleToString(hgf6));

        result.put("hgf7", CommonFunc.convertDoubleToString(hgf7));
        result.put("hgf8", CommonFunc.convertDoubleToString(hgf8));
        result.put("hgf9", CommonFunc.convertDoubleToString(hgf9));
        result.put("hgf10", CommonFunc.convertDoubleToString(hgf10));
        result.put("hgf11", CommonFunc.convertDoubleToString(hgf11));

        result.put("hgf12", CommonFunc.convertDoubleToString(hgf12));
        result.put("hgf13", CommonFunc.convertDoubleToString(hgf13));
        result.put("hgf14", CommonFunc.convertDoubleToString(hgf14));
        result.put("hgf15", CommonFunc.convertDoubleToString(hgf15));
        result.put("afcx1", CommonFunc.convertDoubleToString(afcx1));
        result.put("afcx2", CommonFunc.convertDoubleToString(afcx2));
        result.put("afcx3", CommonFunc.convertDoubleToString(afcx3));
        result.put("afcx4", CommonFunc.convertDoubleToString(afcx4));
        result.put("afcx5", CommonFunc.convertDoubleToString(afcx5));
        result.put("afcx6", CommonFunc.convertDoubleToString(afcx6));
        result.put("afcx7", CommonFunc.convertDoubleToString(afcx7));
        result.put("afcx8", CommonFunc.convertDoubleToString(afcx8));
        result.put("afcx9", CommonFunc.convertDoubleToString(afcx9));
        result.put("afcx10", CommonFunc.convertDoubleToString(afcx10));
        result.put("afcx11", CommonFunc.convertDoubleToString(afcx11));
        result.put("afcx12", CommonFunc.convertDoubleToString(afcx12));
        result.put("afcx13", CommonFunc.convertDoubleToString(afcx13));
        result.put("afcx14", CommonFunc.convertDoubleToString(afcx14));
        result.put("afcx15", CommonFunc.convertDoubleToString(afcx15));
        result.put("aftx1", CommonFunc.convertDoubleToString(aftx1));
        result.put("aftx2", CommonFunc.convertDoubleToString(aftx2));
        result.put("aftx3", CommonFunc.convertDoubleToString(aftx3));
        result.put("aftx4", CommonFunc.convertDoubleToString(aftx4));
        result.put("aftx5", CommonFunc.convertDoubleToString(aftx5));
        result.put("aftx6", CommonFunc.convertDoubleToString(aftx6));
        result.put("aftx7", CommonFunc.convertDoubleToString(aftx7));
        result.put("aftx8", CommonFunc.convertDoubleToString(aftx8));
        result.put("aftx9", CommonFunc.convertDoubleToString(aftx9));
        result.put("aftx10", CommonFunc.convertDoubleToString(aftx10));
        result.put("aftx11", CommonFunc.convertDoubleToString(aftx11));
        result.put("aftx12", CommonFunc.convertDoubleToString(aftx12));
        result.put("aftx13", CommonFunc.convertDoubleToString(aftx13));
        result.put("aftx14", CommonFunc.convertDoubleToString(aftx14));
        result.put("aftx15", CommonFunc.convertDoubleToString(aftx15));
        result.put("wdlyp3", CommonFunc.convertDoubleToString(wdlyp3));
        String wdlyp3y=wdlyp3.equals("有")?"has":"hasn't";
        result.put("wdlyp3y",CommonFunc.convertDoubleToString(wdlyp3y));
        return result;
    }

    private Map<String, Double> createDoublePDF(String language) {
        Map<String, Double> result = new HashMap();
        //计算稳定性0°工作状态自重及载荷产生的倾覆力矩
        Double msla = tsl * lslqg * 10 * 2;
        Double mshla = tshl * lshlqg * 10 * 1.4;
        Double ma1 = m1 * lqg1 * 10 * 1.25;
        Double ma2 = m2 * lqg2 * 10 * 1.25;
        Double ma14 = m14 * lqg14 * 10 * 1.25;
        result.put("msla", msla);
        result.put("mshla", mshla);
        result.put("ma1", ma1);
        result.put("ma2", ma2);
        result.put("ma14", ma14);

        //计算稳定性0°工作状态自重产生的抗倾覆力矩
        Double ma3 = m3 * lqg3 * 10;
        Double ma4 = m4 * lqg4 * 10;
        Double ma5 = m5 * lqg5 * 10;
        Double ma6 = m6 * lqg6 * 10;
        Double ma7 = m7 * lqg7 * 10;
        Double ma8 = m8 * lqg8 * 10;
        Double ma9 = m9 * lqg9 * 10;
        Double ma10 = m10 * lqg10 * 10;
        Double ma11 = m11 * lqg11 * 10;
        Double ma12 = m12 * lqg12 * 10;
        Double ma13 = m13 * lqg13 * 10;
        Double ma15 = m15 * lqg15 * 10;
        result.put("ma3", ma3);
        result.put("ma4", ma4);
        result.put("ma5", ma5);
        result.put("ma6", ma6);
        result.put("ma7", ma7);
        result.put("ma8", ma8);
        result.put("ma9", ma9);
        result.put("ma10", ma10);
        result.put("ma11", ma11);
        result.put("ma12", ma12);
        result.put("ma13", ma13);
        result.put("ma15", ma15);

        //计算稳定性0°工作状态风载荷产生的倾覆力矩（大臂同向）
        Double msltxw = 250 * asltx * hslg * 1.25;
        Double mshltxw = 250 * ashltx * hshlg * 1.25;
        Double mtxw1 = 250 * atx1 * hg1 * 1.25;
        Double mtxw2 = 250 * atx2 * hg2 * 1.25;
        Double mtxw3 = 250 * atx3 * hg3 * 1.25;
        Double mtxw4 = 250 * atx4 * hg4 * 1.25;
        Double mtxw5 = 250 * atx5 * hg5 * 1.25;
        Double mtxw6 = 250 * atx6 * hg6 * 1.25;
        Double mtxw7 = 250 * atx7 * hg7 * 1.25;
        Double mtxw8 = 250 * atx8 * hg8 * 1.25;
        Double mtxw9 = 250 * atx9 * hg9 * 1.25;
        Double mtxw10 = 250 * atx10 * hg10 * 1.25;
        Double mtxw11 = 250 * atx11 * hg11 * 1.25;
        Double mtxw12 = 250 * atx12 * hg12 * 1.25;
        Double mtxw13 = 250 * atx13 * hg13 * 1.25;
        Double mtxw14 = 250 * atx14 * hg14 * 1.25;
        Double mtxw15 = 250 * atx15 * hg15 * 1.25;
        result.put("msltxw", msltxw);
        result.put("mshltxw", mshltxw);
        result.put("mtxw1", mtxw1);
        result.put("mtxw2", mtxw2);
        result.put("mtxw3", mtxw3);
        result.put("mtxw4", mtxw4);
        result.put("mtxw5", mtxw5);
        result.put("mtxw6", mtxw6);
        result.put("mtxw7", mtxw7);
        result.put("mtxw8", mtxw8);
        result.put("mtxw9", mtxw9);
        result.put("mtxw10", mtxw10);
        result.put("mtxw11", mtxw11);
        result.put("mtxw12", mtxw12);
        result.put("mtxw13", mtxw13);
        result.put("mtxw14", mtxw14);
        result.put("mtxw15", mtxw15);

        //计算稳定性非工作状态自重产生的抗倾覆力矩
        Double mfhl1 = m1 * lhl1 * 10;
        Double mfhl2 = m2 * lhl2 * 10;
        Double mfhl3 = m3 * lhl3 * 10;
        Double mfhl4 = m4 * lhl4 * 10;
        Double mfhl5 = m5 * lhl5 * 10;
        Double mfhl6 = m6 * lhl6 * 10;
        Double mfhl9 = m9 * lhl9 * 10;
        Double mfhl10 = m10 * lhl10 * 10;
        Double mfhl11 = m11 * lhl11 * 10;
        Double mfhl12 = m12 * lhl12 * 10 / 2;
        Double mfhl13 = m13 * lhl13 * 10 / 2;
        Double mfhl14 = m14 * lhl14 * 10;
        result.put("mfhl1", mfhl1);
        result.put("mfhl2", mfhl2);
        result.put("mfhl3", mfhl3);
        result.put("mfhl4", mfhl4);
        result.put("mfhl5", mfhl5);
        result.put("mfhl6", mfhl6);
        result.put("mfhl9", mfhl9);
        result.put("mfhl10", mfhl10);
        result.put("mfhl11", mfhl11);
        result.put("mfhl12", mfhl12);
        result.put("mfhl13", mfhl13);
        result.put("mfhl14", mfhl14);

//        计算稳定性非工作状态自重产生的倾覆力矩
        Double mfhl7 = m7 * lhl7 * 10;
        Double mfhl8 = m8 * lhl8 * 10;
        Double mfhl15 = m15 * lhl15 * 10;
        result.put("mfhl7", mfhl7);
        result.put("mfhl8", mfhl8);
        result.put("mfhl15", mfhl15);

        //计算稳定性非工作状态风载荷产生的倾覆力矩（大臂同向）
        Double mftxw1 = pf * aftx1 * hgf1;
        Double mftxw2 = pf * aftx2 * hgf2;
        Double mftxw3 = pf * aftx3 * hgf3;
        Double mftxw4 = pf * aftx4 * hgf4;
        Double mftxw5 = pf * aftx5 * hgf5;
        Double mftxw6 = pf * aftx6 * hgf6;
        Double mftxw7 = pf * aftx7 * hgf7;
        Double mftxw8 = pf * aftx8 * hgf8;
        Double mftxw9 = pf * aftx9 * hgf9;
        Double mftxw10 = pf * aftx10 * hgf10;
        Double mftxw11 = pf * aftx11 * hgf11;
        Double mftxw12 = pf * aftx12 * hgf12;
        Double mftxw13 = pf * aftx13 * hgf13;
        Double mftxw14 = pf * aftx14 * hgf14;
        Double mftxw15 = pf * aftx15 * hgf15;
        result.put("mftxw1", mftxw1);
        result.put("mftxw2", mftxw2);
        result.put("mftxw3", mftxw3);
        result.put("mftxw4", mftxw4);
        result.put("mftxw5", mftxw5);
        result.put("mftxw6", mftxw6);
        result.put("mftxw7", mftxw7);
        result.put("mftxw8", mftxw8);
        result.put("mftxw9", mftxw9);
        result.put("mftxw10", mftxw10);
        result.put("mftxw11", mftxw11);
        result.put("mftxw12", mftxw12);
        result.put("mftxw13", mftxw13);
        result.put("mftxw14", mftxw14);
        result.put("mftxw15", mftxw15);
//        稳定性计算和结果
        Double mq = msla + mshla + ma1 + ma2 + ma14;
        Double mm2 = ma3 + ma4 + ma5 + ma6 + ma7 + ma8 + ma9 + ma10 + ma11 + ma12 + ma13 + ma15;
        Double mtxw = msltxw + mshltxw + mtxw1 + mtxw2 + mtxw3 + mtxw4 + mtxw5 + mtxw6 + mtxw7 + mtxw8 + mtxw9 + mtxw10 + mtxw11 + mtxw12 + mtxw13 + mtxw14 + mtxw15;
        Double mkhl = mfhl1 + mfhl2 + mfhl3 + mfhl4 + mfhl5 + mfhl6 + mfhl9 + mfhl10 + mfhl11 + mfhl12 + mfhl13 + mfhl14;
        Double mqhl = mfhl7 + mfhl8 + mfhl15;
        Double mftxw = mftxw1 + mftxw2 + mftxw3 + mftxw4 + mftxw5 + mftxw6 + mftxw7 + mftxw8 + mftxw9 + mftxw10 + mftxw11 + mftxw12 + mftxw13 + mftxw14 + mftxw15;
        Double mm1 = mq + mtxw;
        Double mmx3 = nwd1 * nwd2 * flsjl * lg;
        Double mmg3 = fdjlszfb * lg;
        Double mm3 = wdlyp3 == "有" ? Math.min(mmx3, mmg3) : mmg3;
        Double mmh1 = mm2 + mm3;
        Double mm1p = mqhl + mftxw;
        Double mmh2 = mkhl + mm3;
        result.put("mq", mq);
        result.put("mm2", mm2);
        result.put("mtxw", mtxw);
        result.put("mkhl", mkhl);
        result.put("mqhl", mqhl);
        result.put("mftxw", mftxw);
        result.put("mm1", mm1);
        result.put("mmx3", mmx3);
        result.put("mmg3", mmg3);
        result.put("mm3", mm3);
        result.put("mmh1", mmh1);
        result.put("mm1p", mm1p);
        result.put("mmh2", mmh2);

        //0°工作状态自重及载荷产生的倾覆力矩
        Double mslqg = tsl * lslqg * 10 * 1.25;
        Double mshlqg = tshl * lshlqg * 10 * 1.25;
        Double mqg1 = m1 * lqg1 * 10 * 1.25;
        Double mqg2 = m2 * lqg2 * 10 * 1.25;
        Double mqg14 = m14 * lqg14 * 10 * 1.25;
        result.put("mslqg", mslqg);
        result.put("mshlqg", mshlqg);
        result.put("mqg1", mqg1);
        result.put("mqg2", mqg2);
        result.put("mqg14", mqg14);

        //工作状态风载荷产生的水平倾覆力矩
        Double mqg3 = m3 * lqg3 * 10 * 1.25;
        Double mqg4 = m4 * lqg4 * 10 * 1.25;
        Double mqg5 = m5 * lqg5 * 10 * 1.25;
        Double mqg6 = m6 * lqg6 * 10 * 1.25;
        Double mqg7 = m7 * lqg7 * 10 * 1.25;
        Double mqg8 = m8 * lqg8 * 10 * 1.25;
        Double mqg9 = m9 * lqg9 * 10 * 1.25;
        Double mqg10 = m10 * lqg10 * 10 * 1.25;
        Double mqg11 = m11 * lqg11 * 10 * 1.25;
        Double mqg12 = m12 * lqg12 * 10 * 1.25;
        Double mqg13 = m13 * lqg13 * 10 * 1.25;
        Double mqg15 = m15 * lqg15 * 10 * 1.25;
        result.put("mqg3", mqg3);
        result.put("mqg4", mqg4);
        result.put("mqg5", mqg5);
        result.put("mqg6", mqg6);
        result.put("mqg7", mqg7);
        result.put("mqg8", mqg8);
        result.put("mqg9", mqg9);
        result.put("mqg10", mqg10);
        result.put("mqg11", mqg11);
        result.put("mqg12", mqg12);
        result.put("mqg13", mqg13);
        result.put("mqg15", mqg15);

        //工作状态风载荷产生的水平倾覆力
        Double mwqsl = 250 * aslcx * hslg * 1.25;
        Double mwqshl = 250 * ashlcx * hshlg * 1.25;
        Double mwq1 = 250 * acx1 * hg1 * 1.25;
        Double mwq2 = 250 * acx2 * hg2 * 1.25;
        Double mwq3 = 250 * acx3 * hg3 * 1.25;
        Double mwq4 = 250 * acx4 * hg4 * 1.25;
        Double mwq5 = 250 * acx5 * hg5 * 1.25;
        Double mwq6 = 250 * acx6 * hg6 * 1.25;
        Double mwq7 = 250 * acx7 * hg7 * 1.25;
        Double mwq8 = 250 * acx8 * hg8 * 1.25;
        Double mwq9 = 250 * acx9 * hg9 * 1.25;
        Double mwq10 = 250 * acx10 * hg10 * 1.25;
        Double mwq11 = 250 * acx11 * hg11 * 1.25;
        Double mwq12 = 250 * acx12 * hg12 * 1.25;
        Double mwq13 = 250 * acx13 * hg13 * 1.25;
        Double mwq14 = 250 * acx14 * hg14 * 1.25;
        Double mwq15 = 250 * acx15 * hg15 * 1.25;
        result.put("mwqsl", mwqsl);
        result.put("mwqshl", mwqshl);
        result.put("mwq1", mwq1);
        result.put("mwq2", mwq2);
        result.put("mwq3", mwq3);
        result.put("mwq4", mwq4);
        result.put("mwq5", mwq5);
        result.put("mwq6", mwq6);
        result.put("mwq7", mwq7);
        result.put("mwq8", mwq8);
        result.put("mwq9", mwq9);
        result.put("mwq10", mwq10);
        result.put("mwq11", mwq11);
        result.put("mwq12", mwq12);
        result.put("mwq13", mwq13);
        result.put("mwq14", mwq14);
        result.put("mwq15", mwq15);

        //0°轮压值计算
        Double mqqg = mslqg + mshlqg + mqg1 + mqg2 + mqg14;
        Double mkqg = mqg3 + mqg4 + mqg5 + mqg6 + mqg7 + mqg8 + mqg9 + mqg10 + mqg11 + mqg12 + mqg13 + mqg15;
        Double mwq = mwqsl + mwqshl + mwq1 + mwq2 + mwq3 + mwq4 + mwq5 + mwq6 + mwq7 + mwq8 + mwq9 + mwq10 + mwq11 + mwq12 + mwq13 + mwq14 + mwq15;
        Double mfqg = mkqg - mqqg;
        Double vcd = mfqg / lg / 2;
        Double vab = 1.25 * mzj * 10 / 2 - vcd;
        Double mgq = 2 * 0.064 * mzj * gxh;
        Double msq = mgq + mwq;
        Double dtv1 = msq / ll / 2;
        Double av1 = vab - dtv1;
        Double bv1 = vab + dtv1;
        Double cv1 = vcd + dtv1;
        Double dv1 = vcd - dtv1;
        result.put("mqqg", mqqg);
        result.put("mkqg", mkqg);
        result.put("mwq", mwq);
        result.put("mfqg", mfqg);
        result.put("vcd", vcd);
        result.put("vab", vab);
        result.put("mgq", mgq);
        result.put("msq", msq);
        result.put("dtv1", dtv1);
        result.put("av1", av1);
        result.put("bv1", bv1);
        result.put("cv1", cv1);
        result.put("dv1", dv1);

        //0°摩擦力计算
        Double at1 = av1 * 0.05;
        Double bt1 = bv1 * 0.05;
        result.put("at1", at1);
        result.put("bt1", bt1);

        //工作状态擦窗机各部件风载荷
        Double fslcx = 250 * aslcx * 1.25;
        Double fshlcx = 250 * ashlcx * 1.25;
        Double fcx1 = 250 * acx1 * 1.25;
        Double fcx2 = 250 * acx2 * 1.25;
        Double fcx3 = 250 * acx3 * 1.25;
        Double fcx4 = 250 * acx4 * 1.25;
        Double fcx5 = 250 * acx5 * 1.25;
        Double fcx6 = 250 * acx6 * 1.25;
        Double fcx7 = 250 * acx7 * 1.25;
        Double fcx8 = 250 * acx8 * 1.25;
        Double fcx9 = 250 * acx9 * 1.25;
        Double fcx10 = 250 * acx10 * 1.25;
        Double fcx11 = 250 * acx11 * 1.25;
        Double fcx12 = 250 * acx12 * 1.25;
        Double fcx13 = 250 * acx13 * 1.25;
        Double fcx14 = 250 * acx14 * 1.25;
        Double fcx15 = 250 * acx15 * 1.25;
        result.put("fslcx", fslcx);
        result.put("fshlcx", fshlcx);
        result.put("fcx1", fcx1);
        result.put("fcx2", fcx2);
        result.put("fcx3", fcx3);
        result.put("fcx4", fcx4);
        result.put("fcx5", fcx5);
        result.put("fcx6", fcx6);
        result.put("fcx7", fcx7);
        result.put("fcx8", fcx8);
        result.put("fcx9", fcx9);
        result.put("fcx10", fcx10);
        result.put("fcx11", fcx11);
        result.put("fcx12", fcx12);
        result.put("fcx13", fcx13);
        result.put("fcx14", fcx14);
        result.put("fcx15", fcx15);

        //工作状态风载荷对擦窗机各部件产生的正向回转力矩
        Double mwhzsl = fslcx * lslhz;
        Double mwhzshl = fshlcx * lshlhz;
        Double mwhz1 = fcx1 * lhz1;
        Double mwhz2 = fcx2 * lhz2;
        Double mwhz3 = fcx3 * lhz3;
        Double mwhz4 = fcx4 * lhz4;
        Double mwhz5 = fcx5 * lhz5;
        Double mwhz14 = fcx14 * lhz14;
        result.put("mwhzsl", mwhzsl);
        result.put("mwhzshl", mwhzshl);
        result.put("mwhz1", mwhz1);
        result.put("mwhz2", mwhz2);
        result.put("mwhz3", mwhz3);
        result.put("mwhz4", mwhz4);
        result.put("mwhz5", mwhz5);
        result.put("mwhz14", mwhz14);

        //工作状态风载荷对擦窗机各部件产生的反向回转力矩
        Double mwhz6 = fcx6 * lhz6;
        Double mwhz7 = fcx7 * lhz7;
        Double mwhz8 = fcx8 * lhz8;
        Double mwhz9 = fcx9 * lhz9;
        Double mwhz10 = fcx10 * lhz10;
        Double mwhz11 = fcx11 * lhz11;
        Double mwhz12 = fcx12 * lhz12;
        Double mwhz13 = fcx13 * lhz13;
        Double mwhz15 = fcx15 * lhz15;
        result.put("mwhz6", mwhz6);
        result.put("mwhz7", mwhz7);
        result.put("mwhz8", mwhz8);
        result.put("mwhz9", mwhz9);
        result.put("mwhz10", mwhz10);
        result.put("mwhz11", mwhz11);
        result.put("mwhz12", mwhz12);
        result.put("mwhz13", mwhz13);
        result.put("mwhz15", mwhz15);

        //0°水平力计算
        Double fwcx = fslcx + fshlcx + fcx1 + fcx2 + fcx3 + fcx4 + fcx5 + fcx6 + fcx7 + fcx8 + fcx9 + fcx10 + fcx11 + fcx12 + fcx13 + fcx14 + fcx15;
        Double mwhza = mwhzsl + mwhzshl + mwhz1 + mwhz2 + mwhz3 + mwhz4 + mwhz5 + mwhz14;
        Double mwhzb = mwhz6 + mwhz7 + mwhz8 + mwhz9 + mwhz10 + mwhz11 + mwhz12 + mwhz13 + mwhz15;
        Double mwhz = mwhza - mwhzb;
        Double dth1 = mwhz / ll;
        Double ah1 = -dth1;
        Double bh1 = dth1;
        result.put("fwcx", fwcx);
        result.put("mwhza", mwhza);
        result.put("mwhzb", mwhzb);
        result.put("mwhz", mwhz);
        result.put("dth1", dth1);
        result.put("ah1", ah1);
        result.put("bh1", bh1);

        //45°工作状态自重及载荷产生的倾覆力矩
        Double mslhz = tsl * lslhz * 10 * 1.25;
        Double mshlhz = tshl * lshlhz * 10 * 1.25;
        Double mhz1 = m1 * lhz1 * 10 * 1.25;
        Double mhz2 = m2 * lhz2 * 10 * 1.25;
        Double mhz3 = m3 * lhz3 * 10 * 1.25;
        Double mhz4 = m4 * lhz4 * 10 * 1.25;
        Double mhz5 = m5 * lhz5 * 10 * 1.25;
        Double mhz14 = m14 * lhz14 * 10 * 1.25;
        result.put("mslhz", mslhz);
        result.put("mshlhz", mshlhz);
        result.put("mhz1", mhz1);
        result.put("mhz2", mhz2);
        result.put("mhz3", mhz3);
        result.put("mhz4", mhz4);
        result.put("mhz5", mhz5);
        result.put("mhz14", mhz14);

        //45°工作状态自重产生的抗倾覆力矩
        Double mhz6 = m6 * lhz6 * 10 * 1.25;
        Double mhz7 = m7 * lhz7 * 10 * 1.25;
        Double mhz8 = m8 * lhz8 * 10 * 1.25;
        Double mhz9 = m9 * lhz9 * 10 * 1.25;
        Double mhz10 = m10 * lhz10 * 10 * 1.25;
        Double mhz11 = m11 * lhz11 * 10 * 1.25;
        Double mhz12 = m12 * lhz12 * 10 * 1.25;
        Double mhz13 = m13 * lhz13 * 10 * 1.25;
        Double mhz15 = m15 * lhz15 * 10 * 1.25;
        result.put("mhz6", mhz6);
        result.put("mhz7", mhz7);
        result.put("mhz8", mhz8);
        result.put("mhz9", mhz9);
        result.put("mhz10", mhz10);
        result.put("mhz11", mhz11);
        result.put("mhz12", mhz12);
        result.put("mhz13", mhz13);
        result.put("mhz15", mhz15);

        //45°轮压值计算
        Double mqhz = mslhz + mshlhz + mhz1 + mhz2 + mhz3 + mhz4 + mhz5 + mhz14;
        Double mkhz = mhz6 + mhz7 + mhz8 + mhz9 + mhz10 + mhz11 + mhz12 + mhz13 + mhz15;
        Double vm = 1.25 * mzj * 10 / 4;
        Double mfhz = mqhz - mkhz;
        Double mfhzx = mfhz * 0.707;
        Double mfhzy = mfhz * 0.707;
        Double dtvx = mfhzx / ll / 2;
        Double dtvy = mfhzy / lg / 2;
        Double dtv2 = msq / Math.sqrt(lg * lg + ll * ll);
        Double av2 = vm - dtvx + dtvy - dtv2;
        Double bv2 = vm + dtvx + dtvy;
        Double cv2 = vm + dtvx - dtvy + dtv2;
        Double dv2 = vm - dtvx - dtvy;
        result.put("mqhz", mqhz);
        result.put("mkhz", mkhz);
        result.put("vm", vm);
        result.put("mfhz", mfhz);
        result.put("mfhzx", mfhzx);
        result.put("mfhzy", mfhzy);
        result.put("dtvx", dtvx);
        result.put("dtvy", dtvy);
        result.put("dtv2", dtv2);
        result.put("av2", av2);
        result.put("bv2", bv2);
        result.put("cv2", cv2);
        result.put("dv2", dv2);

        //45°摩擦力计算
        Double at2 = av2 * 0.05;
        Double bt2 = bv2 * 0.05;
        result.put("at2", at2);
        result.put("bt2", bt2);

        //45°水平力计算
        Double dth2 = mwhz / ll;
        result.put("dth2", dth2);
        Double ah2 = fwcx * 0.707 - dth2;
        result.put("ah2", ah2);
        Double bh2 = fwcx * 0.707 + dth2;
        result.put("bh2", bh2);

        //90°工作状态自重及载荷产生的倾覆力矩
        Double mslql = tsl * lslql * 10 * 1.25;
        result.put("mslql", mslql);
        Double mshlql = tshl * lshlql * 10 * 1.25;
        result.put("mshlql", mshlql);
        Double mql1 = m1 * lql1 * 10 * 1.25;
        result.put("mql1", mql1);
        Double mql2 = m2 * lql2 * 10 * 1.25;
        result.put("mql2", mql2);
        Double mql14 = m14 * lql14 * 10 * 1.25;
        result.put("mql14", mql14);

        //90°工作状态自重产生的抗倾覆力矩
        Double mql3 = m3 * lql3 * 10 * 1.25;
        Double mql4 = m4 * lql4 * 10 * 1.25;
        Double mql5 = m5 * lql5 * 10 * 1.25;
        Double mql6 = m6 * lql6 * 10 * 1.25;
        Double mql7 = m7 * lql7 * 10 * 1.25;
        Double mql8 = m8 * lql8 * 10 * 1.25;
        Double mql9 = m9 * lql9 * 10 * 1.25;
        Double mql10 = m10 * lql10 * 10 * 1.25;
        Double mql11 = m11 * lql11 * 10 * 1.25;
        Double mql12 = m12 * lql12 * 10 * 1.25 / 2;
        Double mql13 = m13 * lql13 * 10 * 1.25 / 2;
        Double mql15 = m15 * lql15 * 10 * 1.25;
        result.put("mql3", mql3);
        result.put("mql4", mql4);
        result.put("mql5", mql5);
        result.put("mql6", mql6);
        result.put("mql7", mql7);
        result.put("mql8", mql8);
        result.put("mql9", mql9);
        result.put("mql10", mql10);
        result.put("mql11", mql11);
        result.put("mql12", mql12);
        result.put("mql13", mql13);
        result.put("mql15", mql15);

        //90°轮压值计算
        Double mqql = mslql + mshlql + mql1 + mql2 + mql14;
        Double mkql = mql3 + mql4 + mql5 + mql6 + mql7 + mql8 + mql9 + mql10 + mql11 + mql12 + mql13 + mql15;
        Double mfql = mkql - mqql;
        Double vad = mfql / ll / 2;
        Double vbc = 1.25 * mzj * 10 / 2 - vad;
        Double dtv3 = msq / lg / 2;
        Double av3 = vad - dtv3;
        Double bv3 = vbc - dtv3;
        Double cv3 = vbc + dtv3;
        Double dv3 = vad + dtv3;
        result.put("mqql", mqql);
        result.put("mkql", mkql);
        result.put("mfql", mfql);
        result.put("vad", vad);
        result.put("vbc", vbc);
        result.put("dtv3", dtv3);
        result.put("av3", av3);
        result.put("bv3", bv3);
        result.put("cv3", cv3);
        result.put("dv3", dv3);

        //90°摩擦力计算
        Double at3 = av3 * 0.05;
        Double bt3 = bv3 * 0.05;
        result.put("at3", at3);
        result.put("bt3", bt3);

        //90°水平力计算
        Double dth3 = mwhz / ll;
        Double ah3 = fwcx / 2 - dth3;
        Double bh3 = fwcx / 2 + dth3;
        result.put("dth3", dth3);
        result.put("ah3", ah3);
        result.put("bh3", bh3);

        //非工作状态风载荷产生的水平倾覆力矩
        Double mwqf1 = pf * afcx1 * hgf1;
        Double mwqf2 = pf * afcx2 * hgf2;
        Double mwqf3 = pf * afcx3 * hgf3;
        Double mwqf4 = pf * afcx4 * hgf4;
        Double mwqf5 = pf * afcx5 * hgf5;
        Double mwqf6 = pf * afcx6 * hgf6;
        Double mwqf7 = pf * afcx7 * hgf7;
        Double mwqf8 = pf * afcx8 * hgf8;
        Double mwqf9 = pf * afcx9 * hgf9;
        Double mwqf10 = pf * afcx10 * hgf10;
        Double mwqf11 = pf * afcx11 * hgf11;
        Double mwqf12 = pf * afcx12 * hgf12;
        Double mwqf13 = pf * afcx13 * hgf13;
        Double mwqf14 = pf * afcx14 * hgf14;
        Double mwqf15 = pf * afcx15 * hgf15;
        result.put("mwqf1", mwqf1);
        result.put("mwqf2", mwqf2);
        result.put("mwqf3", mwqf3);
        result.put("mwqf4", mwqf4);
        result.put("mwqf5", mwqf5);
        result.put("mwqf6", mwqf6);
        result.put("mwqf7", mwqf7);
        result.put("mwqf8", mwqf8);
        result.put("mwqf9", mwqf9);
        result.put("mwqf10", mwqf10);
        result.put("mwqf11", mwqf11);
        result.put("mwqf12", mwqf12);
        result.put("mwqf13", mwqf13);
        result.put("mwqf14", mwqf14);
        result.put("mwqf15", mwqf15);

        //非工作状态轮压值计算
        Double mfhl = mkhl - mqhl;
        Double mwqf = mwqf1 + mwqf2 + mwqf3 + mwqf4 + mwqf5 + mwqf6 + mwqf7 + mwqf8 + mwqf9 + mwqf10 + mwqf11 + mwqf12 + mwqf13 + mwqf14 + mwqf15;
        Double vbcf = mfhl / ll / 2;
        Double vadf = mzjf * 10 / 2 - vbcf;
        Double dtvf = mwqf / lg / 2;
        Double av4 = vadf - dtvf;
        Double bv4 = vbcf - dtvf;
        Double cv4 = vbcf + dtvf;
        Double dv4 = vadf + dtvf;
        result.put("mfhl", mfhl);
        result.put("mwqf", mwqf);
        result.put("vbcf", vbcf);
        result.put("vadf", vadf);
        result.put("dtvf", dtvf);
        result.put("av4", av4);
        result.put("bv4", bv4);
        result.put("cv4", cv4);
        result.put("dv4", dv4);

        //非工作状态擦窗机各部件风载荷
        Double ffcx1 = pf * afcx1;
        Double ffcx2 = pf * afcx2;
        Double ffcx3 = pf * afcx3;
        Double ffcx4 = pf * afcx4;
        Double ffcx5 = pf * afcx5;
        Double ffcx6 = pf * afcx6;
        Double ffcx7 = pf * afcx7;
        Double ffcx8 = pf * afcx8;
        Double ffcx9 = pf * afcx9;
        Double ffcx10 = pf * afcx10;
        Double ffcx11 = pf * afcx11;
        Double ffcx12 = pf * afcx12;
        Double ffcx13 = pf * afcx13;
        Double ffcx14 = pf * afcx14;
        Double ffcx15 = pf * afcx15;
        result.put("ffcx1", ffcx1);
        result.put("ffcx2", ffcx2);
        result.put("ffcx3", ffcx3);
        result.put("ffcx4", ffcx4);
        result.put("ffcx5", ffcx5);
        result.put("ffcx6", ffcx6);
        result.put("ffcx7", ffcx7);
        result.put("ffcx8", ffcx8);
        result.put("ffcx9", ffcx9);
        result.put("ffcx10", ffcx10);
        result.put("ffcx11", ffcx11);
        result.put("ffcx12", ffcx12);
        result.put("ffcx13", ffcx13);
        result.put("ffcx14", ffcx14);
        result.put("ffcx15", ffcx15);

        //非工作状态风载荷对擦窗机各部件产生的正向回转力矩
        Double mwhzf1 = ffcx1 * lhzf1;
        Double mwhzf2 = ffcx2 * lhzf2;
        Double mwhzf3 = ffcx3 * lhzf3;
        Double mwhzf4 = ffcx4 * lhzf4;
        Double mwhzf5 = ffcx5 * lhzf5;
        Double mwhzf14 = ffcx14 * lhzf14;
        result.put("mwhzf1", mwhzf1);
        result.put("mwhzf2", mwhzf2);
        result.put("mwhzf3", mwhzf3);
        result.put("mwhzf4", mwhzf4);
        result.put("mwhzf5", mwhzf5);
        result.put("mwhzf14", mwhzf14);

        //非工作状态风载荷对擦窗机各部件产生的反向回转力矩
        Double mwhzf6 = ffcx6 * lhzf6;
        Double mwhzf7 = ffcx7 * lhzf7;
        Double mwhzf8 = ffcx8 * lhzf8;
        Double mwhzf9 = ffcx9 * lhzf9;
        Double mwhzf10 = ffcx10 * lhzf10;
        Double mwhzf11 = ffcx11 * lhzf11;
        Double mwhzf12 = ffcx12 * lhzf12;
        Double mwhzf13 = ffcx13 * lhzf13;
        Double mwhzf15 = ffcx15 * lhzf15;
        result.put("mwhzf6", mwhzf6);
        result.put("mwhzf7", mwhzf7);
        result.put("mwhzf8", mwhzf8);
        result.put("mwhzf9", mwhzf9);
        result.put("mwhzf10", mwhzf10);
        result.put("mwhzf11", mwhzf11);
        result.put("mwhzf12", mwhzf12);
        result.put("mwhzf13", mwhzf13);
        result.put("mwhzf15", mwhzf15);

        //非工作状态水平力计算
        Double fwcxf = ffcx1 + ffcx2 + ffcx3 + ffcx4 + ffcx5 + ffcx6 + ffcx7 + ffcx8 + ffcx9 + ffcx10 + ffcx11 + ffcx12 + ffcx13 + ffcx14 + ffcx15;
        Double mwhzfa = mwhzf1 + mwhzf2 + mwhzf3 + mwhzf4 + mwhzf5 + mwhzf14;
        Double mwhzfb = mwhzf6 + mwhzf7 + mwhzf8 + mwhzf9 + mwhzf10 + mwhzf11 + mwhzf12 + mwhzf13 + mwhzf15;
        Double mwhzf = mwhzfa - mwhzfb;
        Double dthf = mwhzf / ll;
        Double ah4 = fwcxf / 2 - dthf;
        Double bh4 = fwcxf / 2 + dthf;
        result.put("fwcxf", fwcxf);
        result.put("mwhzfa", mwhzfa);
        result.put("mwhzfb", mwhzfb);
        result.put("mwhzf", mwhzf);
        result.put("dthf", dthf);
        result.put("ah4", ah4);
        result.put("bh4", bh4);


        Double av1k = av1 / 1000;
        Double bv1k = bv1 / 1000;
        Double cv1k = cv1 / 1000;
        Double dv1k = dv1 / 1000;
        Double at1k = at1 / 1000;
        Double bt1k = bt1 / 1000;
        Double ah1k = ah1 / 1000;
        Double bh1k = bh1 / 1000;
        result.put("av1k", av1k);
        result.put("bv1k", bv1k);
        result.put("cv1k", cv1k);
        result.put("dv1k", dv1k);
        result.put("at1k", at1k);
        result.put("bt1k", bt1k);
        result.put("ah1k", ah1k);
        result.put("bh1k", bh1k);

        Double av2k = av2 / 1000;
        Double bv2k = bv2 / 1000;
        Double cv2k = cv2 / 1000;
        Double dv2k = dv2 / 1000;
        Double at2k = at2 / 1000;
        Double bt2k = bt2 / 1000;
        Double ah2k = ah2 / 1000;
        Double bh2k = bh2 / 1000;
        result.put("av2k", av2k);
        result.put("bv2k", bv2k);
        result.put("cv2k", cv2k);
        result.put("dv2k", dv2k);
        result.put("at2k", at2k);
        result.put("bt2k", bt2k);
        result.put("ah2k", ah2k);
        result.put("bh2k", bh2k);

        Double av3k = av3 / 1000;
        Double bv3k = bv3 / 1000;
        Double cv3k = cv3 / 1000;
        Double dv3k = dv3 / 1000;
        Double at3k = at3 / 1000;
        Double bt3k = bt3 / 1000;
        Double ah3k = ah3 / 1000;
        Double bh3k = bh3 / 1000;
        result.put("av3k", av3k);
        result.put("bv3k", bv3k);
        result.put("cv3k", cv3k);
        result.put("dv3k", dv3k);
        result.put("at3k", at3k);
        result.put("bt3k", bt3k);
        result.put("ah3k", ah3k);
        result.put("bh3k", bh3k);

        Double av4k = av4 / 1000;
        Double bv4k = bv4 / 1000;
        Double cv4k = cv4 / 1000;
        Double dv4k = dv4 / 1000;
        Double ah4k = ah4 / 1000;
        Double bh4k = bh4 / 1000;
        result.put("av4k", av4k);
        result.put("bv4k", bv4k);
        result.put("cv4k", cv4k);
        result.put("dv4k", dv4k);
        result.put("ah4k", ah4k);
        result.put("bh4k", bh4k);

        return result;
    }

    private String createSign(Boolean b) {
        return b ? "≥" : "<";
    }

    private String createString(Boolean b) {
        return b ? "满足" : "不满足";
    }
    private String createEnString(Boolean b) {
        return b ? "meets" : "doesn't meet";
    }
    public Map<String, String> createMapForPDF(String language) {
        Map<String, Double> doubleMap = createDoublePDF("CN");
        Map<String, String> map = createMap();
        Double mmh1 = doubleMap.get("mmh1");
        Double mm1 = doubleMap.get("mm1");
        Double mmh2 = doubleMap.get("mmh2");
        Double mm1p = doubleMap.get("mm1p");
        String wdlyp1 = createSign(mmh1 >= mm1);
        String wdlym1 = createString(mmh1 >= mm1);
        String wdlym1y = createEnString(mmh1 >= mm1);

        String wdlyp2 = createSign(mmh2 >= mm1p);
        String wdlym2 = createString(mmh2 >= mm1p);
        String wdlym2y = createEnString(mmh2 >= mm1p);
        String wdlym3 = createString(mmh2 >= mm1p && mmh1 >= mm1);
        String wdlym3y = createEnString(mmh2 >= mm1p && mmh1 >= mm1);
        Map<String, String> resultMap = new HashMap<>();
        resultMap.put("wdlyp1", wdlyp1);
        resultMap.put("wdlym1", wdlym1);
        resultMap.put("wdlym1y", wdlym1y);
        resultMap.put("wdlyp2", wdlyp2);
        resultMap.put("wdlym2", wdlym2);
        resultMap.put("wdlym3", wdlym3);
        resultMap.put("wdlym2y", wdlym2y);
        resultMap.put("wdlym3y", wdlym3y);
        for (Map.Entry<String, Double> e : doubleMap.entrySet()) {
            resultMap.put(e.getKey(), CommonFunc.convertDoubleToString(e.getValue()));
        }
        for (Map.Entry<String, String> e : map.entrySet()) {
            resultMap.put(e.getKey(), e.getValue());
        }
        return resultMap;
    }

    public Map<String, String> createMapForCheckPDF(String language) {
        Map<String, Double> doubleMap = createDoublePDF(language);
        Double mzj = this.mzj;
        Double mfhz = doubleMap.get("mfhz");
        Double msq = doubleMap.get("msq");
        Double fwcx = doubleMap.get("fwcx");
        Double mwhz = doubleMap.get("mwhz");
        Double lg = this.lg;
        Double ll = this.ll;
        Double av2 = doubleMap.get("av2");
        Double bv2 = doubleMap.get("bv2");
        Double cv2 = doubleMap.get("cv2");
        Double dv2 = doubleMap.get("dv2");
        Double at2 = doubleMap.get("at2");
        Double bt2 = doubleMap.get("bt2");
        Double ah2 = doubleMap.get("ah2");
        Double bh2 = doubleMap.get("bh2");

        Double dtvm = 1.25 * mzj * 10 / 4;
        Double dtvfy = mfhz / Math.sqrt(lg * lg + ll * ll);
        Double dtvw = msq / Math.sqrt(lg * lg + ll * ll);
        Double dthh = mwhz / ll;
        Double av5 = dtvm + 0 - dtvw;
        Double bv5 = dtvm + dtvfy + 0;
        Double cv5 = dtvm - 0 + dtvw;
        Double dv5 = dtvm - dtvfy - 0;
        Double at5 = av5 * 0.05;
        Double bt5 = bv5 * 0.05;
        Double ah5 = fwcx * 0.707 - dthh;
        Double bh5 = fwcx * 0.707 + dthh;
        Double wdlyyzb1 = av2 / av5;
        Double wdlyyzb2 = bv2 / bv5;
        Double wdlyyzb3 = cv2 / cv5;
        Double wdlyyzb4 = dv2 / dv5;
        Double wdlyyzb5 = at2 / at5;
        Double wdlyyzb6 = bt2 / bt5;
        Double wdlyyzb7 = ah2 / ah5;
        Double wdlyyzb8 = bh2 / bh5;
        String wdlyyzp1 = 0.85 <= wdlyyzb1 && wdlyyzb1 <= 1.15 ? "符合" : "不符合";
        String wdlyyzp2 = 0.85 <= wdlyyzb2 && wdlyyzb2 <= 1.15 ? "符合" : "不符合";
        String wdlyyzp3 = 0.85 <= wdlyyzb3 && wdlyyzb3 <= 1.15 ? "符合" : "不符合";
        String wdlyyzp4 = 0.85 <= wdlyyzb4 && wdlyyzb4 <= 1.15 ? "符合" : "不符合";
        String wdlyyzp5 = 0.85 <= wdlyyzb5 && wdlyyzb5 <= 1.15 ? "符合" : "不符合";
        String wdlyyzp6 = 0.85 <= wdlyyzb6 && wdlyyzb6 <= 1.15 ? "符合" : "不符合";
        String wdlyyzp7 = 0.85 <= wdlyyzb7 && wdlyyzb7 <= 1.15 ? "符合" : "不符合";
        String wdlyyzp8 = 0.85 <= wdlyyzb8 && wdlyyzb8 <= 1.15 ? "符合" : "不符合";

        Map<String, String> map = new HashMap<>();

        map.put("mzj", CommonFunc.convertDoubleToString(mzj));
        map.put("mfhz", CommonFunc.convertDoubleToString(mfhz));
        map.put("msq", CommonFunc.convertDoubleToString(msq));
        map.put("fwcx", CommonFunc.convertDoubleToString(fwcx));
        map.put("mwhz", CommonFunc.convertDoubleToString(mwhz));
        map.put("lg", CommonFunc.convertDoubleToString(lg));
        map.put("ll", CommonFunc.convertDoubleToString(ll));
        map.put("av2", CommonFunc.convertDoubleToString(av2));
        map.put("bv2", CommonFunc.convertDoubleToString(bv2));
        map.put("cv2", CommonFunc.convertDoubleToString(cv2));
        map.put("dv2", CommonFunc.convertDoubleToString(dv2));
        map.put("at2", CommonFunc.convertDoubleToString(at2));
        map.put("bt2", CommonFunc.convertDoubleToString(bt2));
        map.put("ah2", CommonFunc.convertDoubleToString(ah2));
        map.put("bh2", CommonFunc.convertDoubleToString(bh2));
        map.put("dtvm", CommonFunc.convertDoubleToString(dtvm));
        map.put("dtvfy", CommonFunc.convertDoubleToString(dtvfy));
        map.put("dtvw", CommonFunc.convertDoubleToString(dtvw));
        map.put("dthh", CommonFunc.convertDoubleToString(dthh));
        map.put("av5", CommonFunc.convertDoubleToString(av5));
        map.put("bv5", CommonFunc.convertDoubleToString(bv5));
        map.put("cv5", CommonFunc.convertDoubleToString(cv5));
        map.put("dv5", CommonFunc.convertDoubleToString(dv5));
        map.put("at5", CommonFunc.convertDoubleToString(at5));
        map.put("bt5", CommonFunc.convertDoubleToString(bt5));
        map.put("ah5", CommonFunc.convertDoubleToString(ah5));
        map.put("bh5", CommonFunc.convertDoubleToString(bh5));
        map.put("wdlyyzb1", CommonFunc.convertDoubleToString(wdlyyzb1));
        map.put("wdlyyzb2", CommonFunc.convertDoubleToString(wdlyyzb2));
        map.put("wdlyyzb3", CommonFunc.convertDoubleToString(wdlyyzb3));
        map.put("wdlyyzb4", CommonFunc.convertDoubleToString(wdlyyzb4));
        map.put("wdlyyzb5", CommonFunc.convertDoubleToString(wdlyyzb5));
        map.put("wdlyyzb6", CommonFunc.convertDoubleToString(wdlyyzb6));
        map.put("wdlyyzb7", CommonFunc.convertDoubleToString(wdlyyzb7));
        map.put("wdlyyzb8", CommonFunc.convertDoubleToString(wdlyyzb8));
        map.put("wdlyyzp1", CommonFunc.convertDoubleToString(wdlyyzp1));
        map.put("wdlyyzp2", CommonFunc.convertDoubleToString(wdlyyzp2));
        map.put("wdlyyzp3", CommonFunc.convertDoubleToString(wdlyyzp3));
        map.put("wdlyyzp4", CommonFunc.convertDoubleToString(wdlyyzp4));
        map.put("wdlyyzp5", CommonFunc.convertDoubleToString(wdlyyzp5));
        map.put("wdlyyzp6", CommonFunc.convertDoubleToString(wdlyyzp6));
        map.put("wdlyyzp7", CommonFunc.convertDoubleToString(wdlyyzp7));
        map.put("wdlyyzp8", CommonFunc.convertDoubleToString(wdlyyzp8));
        return map;
    }

    public Map<String, String> checkCN(String language) {
        Map<String, String> map = createMapForPDF(language);
        Map<String, String> result = new HashMap<>();
        result.put("wdlym1", map.get("wdlym1"));
        result.put("wdlym2", map.get("wdlym2"));
        result.put("x2", map.get("x2"));
        result.put("x4", map.get("x4"));
        result.put("av1k", map.get("av1k"));
        result.put("bv1k", map.get("bv1k"));
        result.put("cv1k", map.get("cv1k"));
        result.put("dv1k", map.get("dv1k"));
        result.put("at1k", map.get("at1k"));
        result.put("bt1k", map.get("bt1k"));
        result.put("ah1k", map.get("ah1k"));
        result.put("bh1k", map.get("bh1k"));
        result.put("av2k", map.get("av2k"));
        result.put("bv2k", map.get("bv2k"));
        result.put("cv2k", map.get("cv2k"));
        result.put("dv2k", map.get("dv2k"));
        result.put("at2k", map.get("at2k"));
        result.put("bt2k", map.get("bt2k"));
        result.put("ah2k", map.get("ah2k"));
        result.put("bh2k", map.get("bh2k"));
        result.put("av3k", map.get("av3k"));
        result.put("bv3k", map.get("bv3k"));
        result.put("cv3k", map.get("cv3k"));
        result.put("dv3k", map.get("dv3k"));
        result.put("at3k", map.get("at3k"));
        result.put("bt3k", map.get("bt3k"));
        result.put("ah3k", map.get("ah3k"));
        result.put("bh3k", map.get("bh3k"));
        result.put("av4k", map.get("av4k"));
        result.put("bv4k", map.get("bv4k"));
        result.put("cv4k", map.get("cv4k"));
        result.put("dv4k", map.get("dv4k"));
        result.put("at4k", map.get("at4k"));
        result.put("bt4k", map.get("bt4k"));
        result.put("ah4k", map.get("ah4k"));
        result.put("bh4k", map.get("bh4k"));
        return result;
    }


}
